//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Badaczek.Identity.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Badaczek.Identity.Web.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_ConcurrencyFailure.
        /// </summary>
        public static string Identity_ConcurrencyFailure {
            get {
                return ResourceManager.GetString("Identity_ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultError.
        /// </summary>
        public static string Identity_DefaultError {
            get {
                return ResourceManager.GetString("Identity_DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already taken..
        /// </summary>
        public static string Identity_DuplicateEmail {
            get {
                return ResourceManager.GetString("Identity_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Role name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string Identity_DuplicateRoleName {
            get {
                return ResourceManager.GetString("Identity_DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &apos;{0}&apos; is already taken..
        /// </summary>
        public static string Identity_DuplicateUserName {
            get {
                return ResourceManager.GetString("Identity_DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is invalid..
        /// </summary>
        public static string Identity_InvalidEmail {
            get {
                return ResourceManager.GetString("Identity_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string Identity_InvalidRoleName {
            get {
                return ResourceManager.GetString("Identity_InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_InvalidToken.
        /// </summary>
        public static string Identity_InvalidToken {
            get {
                return ResourceManager.GetString("Identity_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username {0} is invalid, can only contain letters or digits..
        /// </summary>
        public static string Identity_InvalidUserName {
            get {
                return ResourceManager.GetString("Identity_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_LoginAlreadyAssociated.
        /// </summary>
        public static string Identity_LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("Identity_LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_PasswordMismatch.
        /// </summary>
        public static string Identity_PasswordMismatch {
            get {
                return ResourceManager.GetString("Identity_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_PasswordRequiresDigit.
        /// </summary>
        public static string Identity_PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("Identity_PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_PasswordRequiresLower.
        /// </summary>
        public static string Identity_PasswordRequiresLower {
            get {
                return ResourceManager.GetString("Identity_PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_PasswordRequiresNonAlphanumeric.
        /// </summary>
        public static string Identity_PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("Identity_PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must use at least {0} different characters..
        /// </summary>
        public static string Identity_PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("Identity_PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_PasswordRequiresUpper.
        /// </summary>
        public static string Identity_PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("Identity_PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least {0} characters..
        /// </summary>
        public static string Identity_PasswordTooShort {
            get {
                return ResourceManager.GetString("Identity_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_RecoveryCodeRedemptionFailed.
        /// </summary>
        public static string Identity_RecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("Identity_RecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_UserAlreadyHasPassword.
        /// </summary>
        public static string Identity_UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("Identity_UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already in role &apos;{0}&apos;..
        /// </summary>
        public static string Identity_UserAlreadyInRole {
            get {
                return ResourceManager.GetString("Identity_UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity_UserLockoutNotEnabled.
        /// </summary>
        public static string Identity_UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("Identity_UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in role &apos;{0}&apos;.
        /// </summary>
        public static string Identity_UserNotInRole {
            get {
                return ResourceManager.GetString("Identity_UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg_test.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register_button.
        /// </summary>
        public static string Register_button {
            get {
                return ResourceManager.GetString("Register_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register_CreateAccount.
        /// </summary>
        public static string Register_CreateAccount {
            get {
                return ResourceManager.GetString("Register_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.FirstName.
        /// </summary>
        public static string Register_FirstName {
            get {
                return ResourceManager.GetString("Register_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.LastName.
        /// </summary>
        public static string Register_LastName {
            get {
                return ResourceManager.GetString("Register_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register_Password.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register_PreferredLanguage.
        /// </summary>
        public static string Register_PreferredLanguage {
            get {
                return ResourceManager.GetString("Register_PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register_ResearchUnit.
        /// </summary>
        public static string Register_ResearchUnit {
            get {
                return ResourceManager.GetString("Register_ResearchUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register_Title.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation_Confirm_password.
        /// </summary>
        public static string Validation_Confirm_password {
            get {
                return ResourceManager.GetString("Validation_Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string Validation_Passwd {
            get {
                return ResourceManager.GetString("Validation_Passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation_passwd_not_mach.
        /// </summary>
        public static string Validation_passwd_not_match {
            get {
                return ResourceManager.GetString("Validation_passwd_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.Required.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
